### ISSUE TITLE
How come we only wrap try-catch for modules and not services?

### ISSUE THREAD

**Issue by trunghung** [box/t3js#102]
I see in the code we appear to only captureObjectErrors for modules.  what about services methods?  It would be nice if we can capture errors from those as well. thanks

**Comment by nzakas** [comment]
It's not necessary to wrap service methods because they are called from module methods that are already wrapped, so you still get the benefit.

**Comment by trunghung** [comment]
The reason that I am asking is that I have certain services that exists independently of the UI modules.  They serve as a connecting bridge between our legacy code and the new world of T3js.  Another benefits of wrapping is services is that if there is an exception, then we would know the exception occurred inside the service rather than we see the exception belong to the module since that's the name we provided.

**Comment by nzakas** [comment]
Services are a lot harder to wrap automatically because:

1. You can return anything as a service: a function, a Boolean, an object, etc.
1. For module methods, no one is calling them directly and they don't return anything. We can't make those same assumptions about service methods, so wrapping them and returning nothing could cause a cascade of other errors that would be hard to track down.

So, I don't think this is something T3 should be doing, as we just can't know how to handle it safely as we can with modules.

I'd suggest creating something yourself to behave in a way that makes sense for your application. It takes very little code: https://www.nczonline.net/blog/2009/04/28/javascript-error-handling-anti-pattern/

**Comment by j3tan** [comment]
Closing this issue, please read above.
