### ISSUE TITLE
Add mousemove to DOMEventDelegate

### ISSUE THREAD

**Issue by dreki** [box/t3js#124]
I've written a module that uses mousemove to draw onto a canvas. I had to bind this manually. Please add this to the list of supported events in DOMEventDelegate. The event bubbles so there aren't problems there.

**Comment by j3tan** [comment]
We'll add it in for 2.0

**Comment by nzakas** [comment]
There's a performance consideration here. Since T3 attaches events at the module level, every mouse movement within that module will trigger the event handler. IIRC, that's why we didn't add it initially. Could be a "pro user" feature, so you accept this downside when using it, by just wanted to point that out.

**Comment by j3tan** [comment]
Yeah, we can probably put a warning in our documentation as well as a list of events supported.

**Comment by dreki** [comment]
This is true of vanilla js as well. People should just know this in general.
