### ISSUE TITLE
Unloading a module for hot reloading

### ISSUE THREAD

**Issue by zephraph** [box/t3js#139]
I've been thinking about how T3 might function with a hot reloading system. Let's say you had a websocket client attached to your page that received changes from the server. The page loads up, you add your modules, and t3 initializes them. When a change comes in via the websocket you could call destroy on the module to clean it up, but there's no real way to "remove" the module from the application object so that you can essentially load in a new version. 

Aside from adding methods like `removeModule`, `removeService`, etc would there be anyway currently to swap out the constructed module body with another version of it? If not, is there any thought to how difficult this addition would be?

**Comment by j3tan** [comment]
A hot reload feature seems like a pretty unique use-case. While it would be fairly easy to add a `removeModule` and `removeService` function, I wouldn't recommend it. You'd likely need the Application object to verify that nothing is using or has a reference to the component you are removing. 

Then there are some other use cases, for example:
```
var someService = Box.Application.getService('some-service');
Box.Application.removeService('some-service');

someService.foo();
```

Technically, `foo()` will still execute fine since the `getService` returns an instance of the service, and `removeService()` would be de-registering the 'creator' function.

I'd probably opt more for having unique module/service names than deregistering components. I don't think many people will hit memory consumption issues anyway.

**Comment by zephraph** [comment]
So you have a good point on a service. In that case perhaps hot reloading wouldn't be applicable. I feel like it would still work for modules and behaviors though. Those are decoupled by default and there shouldn't be floating instances. Behaviors are a bit tricker because they'd need to be reapplied any to any modules... I don't know. I'll figure something out.

**Comment by JanisSharma** [comment]
if 'myModule' in sys.modules:
del sys.modules["myModule"]

Full Source At [Here](https://icetutor.com/question/how-do-i-unload-reload-a-module/)
