### ISSUE TITLE
New onmessage handler cannot use module methods

### ISSUE THREAD

**Issue by j3tan** [box/t3js#164]
So after trying to test the new `onmessage` handlers, I ran into a problem with how the object is bound
```
Box.Application.addModule('foo', function (context) {
	'use strict';
	return {

		onmessage: {
			somemessage: this.handleSomeMessage
		},

		handleSomeMessage: function(data) {
			console.log(data);
		},

	};
});
```

So `this.handleSomeMessage` isn't set correctly since `this` isn't fully defined when creating the `onmessage` object. This results in `Uncaught TypeError: Cannot read property 'call' of undefined(…)` since `instance.onmessage['somemessage']` is `undefined`. Moving the handleSomeMessage function declaration higher doesn't do anything. A developer would have to do something like

```
Box.Application.addModule('foo', function (context) {
	'use strict';

	var module = {

		handleSomeMessage: function(data) {
			console.log(data);
		},

	};

	// Bind after module object is created
	module.onmessage = {
		somemessage: module.handleSomeMessage
	};
});
```

Alternatively, this could work as well but it defeats half the purpose of the new onmessage:

```
Box.Application.addModule('foo', function (context) {
	'use strict';
	return {

		onmessage: {
			somemessage: function(data) {
				this.handleSomeMessage(data);
			}
		},

		handleSomeMessage: function(data) {
			console.log(data);
		},

	};
});
```
We should also modify the test case in `application-test` since checking if this.onmessage exists is insufficient as it will 'exist' at the point of checking.

**Comment by j3tan** [comment]
I'm looking for other options around this that don't involve modifying the way developers write behaviors/modules

**Comment by j3tan** [comment]
@zephraph - Thoughts?

**Comment by nzakas** [comment]
I thought the use case for this change was to do stuff like this?

```js
Box.Application.addModule('foo', function (context) {
    'use strict';
    return {

        onmessage: {
            somemessage: function(data) {
                console.log(data);
                this.somethingElse();
            }
        }
    };
});
```

So that `this` inside of `somemessage` is bound to the module instance itself? 

I guess this is to say, it seems like it's working the way it was intended. 

If the use case is instead that you only want to specify which function to call when a message is received, then you'd be better off assigning to a string that can be looked up on the module, like this:

```js
Box.Application.addModule('foo', function (context) {
    'use strict';
    return {

        onmessage: {
            somemessage: "handleSomeMessage",
        },

        handleSomeMessage: function(data) {
            console.log(data);
        },

    };
});
```

**Comment by j3tan** [comment]
It sounds like the 2nd version is closer to our end goal. We want to decouple the logic inside `onmessage` and force developers to delegate the work to other functions. The 1st version doesn't gain any of that delegation power over a normal switch statement, though it does remove the need for a 'messages' array. That said, writing tests for the 2nd version of `onmessage` would be less straight forward.

**Comment by j3tan** [comment]
Alright, going back to the original issue #145, I can see that just having separate functions for each message was a decent enough outcome. The string method mapping seems less intuitive so I'll be closing this issue.

**Comment by zephraph** [comment]
It seems to be working in line with my original intent though perhaps that wasn't communicated well. The only purpose of exposing the message handler on the module instance in my mind would be to make it easier to test. Ultimately though I believe we've achieved that with this approach.

```javascript
Box.Application.addModule('mod', function(context) {

   function someActionHandler(data) {
      // ...
   }

  return {
    onmessage: {
       doThing: function(data) {
         // ...
       },
       anotherMessage: someActionHandler
    }
  }
});
```

Then under test I could access each via
```
Box.getModuleForTest('mod', {}).onmessage.doThing
```

The point was mostly just to force method delegation by providing the object interface. You're right, mostly all that does is removes the switch statement, but by doing that we discourage adding extra logic because it's convenient.
