### ISSUE TITLE
Questions on best practice to inject a dynamic module and ReactJS adoption?

### ISSUE THREAD

**Issue by trunghung** [box/t3js#170]
What's the best practice in T3js to dynamically inject a new module into the page.  Would the module's parent module be the one who inject the container element and call startAll on it?  Also should the module itself or the parent take care of cleaning up the module when it needs to be removed?  Also we are considering adopting ReactJS in our client, I was wondering how is everyone's experience with running T3js and ReactJS?

**Comment by j3tan** [comment]
We combine T3 and ReactJS at Box for several projects and I will be honest that mixing the two comes with its own set of problems. The difficulty is mostly in mixing module systems. With ReactJS, you will likely use ES6/CommonJS, JSX, and some sort of bundler like webpack. Having access to CommonJS makes a few things like `getService`  obsolete since you can just `import` the service instead. That said, we have a huge application and building isolated, complex UI components in ReactJS works really well for both reusability and testability. If you choose to go down this path, I recommend using a T3 service wrapper around your React components and use T3 modules to handle their lifecycle (bind/mount/unmount).
