### ISSUE TITLE
What's the best practice for managing multiple instances of a dynamic module

### ISSUE THREAD

**Issue by trunghung** [box/t3js#171]
I have a module that can have multiple instances on the same page.  What's the best practice for the App to make the lifecycle of these instances?  In my app, I have a widget module that can be injected into the app with multiple instance, and I would like to shutdown one of those instances. Is it customary that a dynamic module manages its own clean up itself and shutdown or the app does that?  How would the app signal to a particular module instance that it should either clean up itself or be prepared to be deleted since all the messages are broadcasted to all the modules and all their instances?  I have a few ideas but it all seems kinda hacky.  Can someone share a good practice on this scenario? thanks

**Comment by j3tan** [comment]
1. Modules do not handle their own life cycle, usually a service or parent module will handle that by calling `.start()` and `.stop()` on the module element.

2. Widgets are typically created as services, not modules. This should make things a lot easier for you since you can add your own `init()` and `destroy()` method to the service widget and handle lifecycle in the parent module. We follow a factory pattern for creating these multi-instance widgets.

```
Box.Application.addService('datepicker', function() {

    function DatePicker(options) {
        ...
    }

    DatePicker.prototype.init = function() {
    };

    DatePicker.prototype.destroy = function() {
    };

    return {
       create: function(options) {
           return new DatePicker(options);
       } 
   };
});
```
Then in your module:
```
Box.Application.addModule('foo', function(context) {
   var datepicker;
    return {
        init: function() {
           var DatePickerFactory = context.getService('datepicker');
            datepicker = DatePickerFactory.create();
            datepicker.init(); // Keep initialization logic outside of the datepicker constructor
        },

        destroy: function() {
            datepicker.destroy();
        }
        
    };

});
```

This is a rough sketch of how we would implement reusable widgets.

**Comment by trunghung** [comment]
thanks.  this is exactly what I had in mind.  thanks

**Comment by trunghung** [comment]
Hi @j3tan , one more question, in this pattern of widget, how would the widget module signal to the service that it wants to shutdown so the wrapping service can delete the module?  One way I can think of would be the module fire an event and pass in the viewport element as an identifier. thanks

**Comment by j3tan** [comment]
Yeah, the widgets should be firing events (you should probably just mix-in EventTarget) and the parent module just needs to listen to the event to know when to destroy the widget. I'm not sure why you need to pass the viewport element though.

**Comment by trunghung** [comment]
@j3tan  Let's say I have class factory A that wraps module B. Each instance of A will wrap an instance of B.  If one instance of B needs to shutdown, B would need to fire an event to the instance of A.  Since app.fire will be broadcasted to all the instances of A, how would the instance of A know that this event came from its instance of B so I can clean up B and itself?

**Comment by j3tan** [comment]
Ah, so you're using a factory service to produce service widgets that contain modules. We do this for popouts/modals but ours are singletons so we don't run into the problem of finding the parent service widget for a given module. That said, the easiest way to do this is not to use the application message bus, but custom DOM events. Since the service widget has a reference to the DOM node that represents the module, you can bind custom event handlers. Just fire an event from the T3 module on the module element and listen to it from the service.

See https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent

If you are using jQuery, its also pretty trivial to `.fire()` and `.on()`
