### ISSUE TITLE
Discussion - multiple points

### ISSUE THREAD

**Issue by nsisodiya** [box/t3js#27]
I have been working with Single page application from last 3-4 year. I liked @nzakas 's video on and implemented a slightly modified version for scalable arch with Javascript. So, I want to discuss my experience.
Before I write, I want to thanks @nzakas for video+books. I consider you are my Teacher too. :)

Here is the link of library I made. https://github.com/nsisodiya/choona.js , We at Unicommerce are using this library in production from last 1.5 years. 

So here are few points to discuss.

Events
=====
Every module is registering 16 events. I see a array ```eventTypes```. I think this is not a good idea. In choona.js, I have used backbone view syntax.
```
        events : {
            "click #submitBtn" : "onSubmitBtnClick"
        },
```
I must say, t3.js should take this approach, mainly because
* Register events which use need.
* Simple syntax, and not need to make lots of if/else like
```
    if (elementType === 'new-todo-input') {
    }
```

Module Definition
============
I noticed that, t3.js has module definition where we need to create a function which return module object. you are passing context which is basically a sandbox (If I am not wrong).
Instead of this, we can use Constructor pattern too. In my opinion this will save memory with common methods over prototype chain.

Dynamic modules/Views + recursively destroy
==================================
I noticed that most of the html present in index.html itself. In most SASS based app, everything is dynamically loaded. Server send almost empty html page and every module load its own html using template property or simple moduleEle.innerHTML etc. Every module further load some sub-module. submodule loading is provided using methods which are provided by sandbox/context. In my current implementation, every module has a registry for its submodule. Why this registry should be maintained by module ? because when top-level router want to "UN-LOAD" a module, all its submodule much be ended. Its like calling ```destroy``` function recursively.
I am unable to see such such recursiveness. May be this is not for t3.js.
Also, It will be great If we can have some demo/guideline for applications which has every module load dynamic html. Or t3.js is best suitable for web-apps which are server side rendered.

Demo
=====
In demo, http://t3js.org/examples/todo/live/ , new dynamic todo is added and functionality is added using behavior. https://github.com/box/t3js/blob/gh-pages/examples/todo/live/js/behaviors/todo.js . I am unable to get difference between module and behaviors. I think, module & behavior share common context and both moduleEl.

PS: Thanks for nice library.

**Comment by nzakas** [comment]
Thanks for the feedback. Here's some answers/context:

> I must say, t3.js should take this approach (Backbone events)

We considered this very early on in the design of T3 and decided against it. In most cases, we went with the minimum viable approach to design so that we'd have room to add things in the future. We may revisit in the future, but we've not had any problems with the current approach to events.

> you are passing context which is basically a sandbox (If I am not wrong).

You are correct. After years of thinking, I decided that "sandbox" was the wrong term for this object.

> Instead of this, we can use Constructor pattern too. In my opinion this will save memory with common methods over prototype chain (module definition)

The memory savings are trivial in this case, and there is zero memory savings when creating a single instance of a module. Maybe if we were dealing with 100,000 instances of modules then we might need to worry more about memory, but in practice there's usually less than 10 modules per page, so memory isn't a big factor in the design.

> I am unable to see such such recursiveness. May be this is not for t3.js.

T3 explicitly does not allow modules to know about each other, so there is no concept of "top-level module" that will control child modules. There is no parent-child relationship - this idea is very much a construct of views in an MVC architecture and is not present in T3.

> Or t3.js is best suitable for web-apps which are server side rendered.

T3 is designed with progressive enhancement in mind, so it expects markup to exist already. It is possible to dynamically load new modules, you'd just grab HTML from the server, ensure the module JS is loaded, and then call `Box.Application.startAll()` on the new DOM structure.

>  I am unable to get difference between module and behaviors. I think, module & behavior share common context and both moduleEl.

Behaviors share the context of the module they are attached to. Some documentation is helpful for understanding the difference:

* http://t3js.org/docs/guides/behaviors
* http://t3js.org/docs/guides/thinking-in-t3
