### ISSUE TITLE
Question: iframe inside a module

### ISSUE THREAD

**Issue by DenMesh** [box/t3js#39]
I have an iframe inside one of my modules. The iframe conforms to same-origin policy - in other words, I can reach inside and do all kinds of stuff with its DOM with just jQuery. The question itself is as follows:
1. Can I use any of T3's event handling capabilities, or am I bound to using plain old jQuery's 'on' method?
2. Can I create a module that encompasses the CONTENTS of the iframe (not the iframe element, but the DOM inside)?

**Comment by j3tan** [comment]
1. I don't think an iframe event bubble to the parent which makes handling the events with a T3 module not possible. You can try assigning the iframe itself as a module, but I have not tested this to verify that it will handle events properly. I'd suggest using the module to managing binding the jQuery event handlers to the iframe (via init/destroy)

2. I don't have too much experience with Same-Origin iframes but technically you should be able to call application.startAll( ... ) on the iframe contents and T3 will bind event handlers. That said, I'm pretty it is a bad idea since necessary javascript variables might be out of scope.

IMO, stick with jQuery event handlers bound from the module that encompasses the iframe (use init/destroy to manage binding/clean up)
