### ISSUE TITLE
[question] module lifecycle

### ISSUE THREAD

**Issue by chchrist** [box/t3js#57]
When we init() the application we do a startAll. There are cases though that we don't want to start a module on init but after an action or after another module has been started. Do you handle cases like these in projects made with t3js? Is it possible to specify the starting order?

**Comment by j3tan** [comment]
At this time, there is no built-in way to delay the 'start' of a module when application `init()` is called. A workaround would be to not apply a data-module attribute to the element until after you are ready, then calling `start()` on it, but that isn't elegant either.

I'm not even sure having a module start order is something we want to support simply because it implies coupling between modules which we purposefully avoid. That said, we did explore at one point an additional attribute like `data-init-delay=true` that would not tell application not to start the module on init and instead, only on an explicit `start()`. The team will review whether this is something we want to support.

**Comment by chchrist** [comment]
I agree that module order implies coupling but lazy initialisation should be considered cause in many cases improves performance

**Comment by nzakas** [comment]
`Box.Application.init()` is just this:

```js
		init: function(params) {

                        // basically Box.Application.setGlobalConfig(params)
			assign(globalConfig, params || {});

			this.startAll(document.documentElement);

			this.fire('init');
			initialized = true;
		},
```

`initialized` is not actually used for anything, so you can ignore that.

If you want a custom way of starting modules, you could just call `setGlobalConfig()` and `startAll()` yourself in whatever way you want.

As Jeff mentioned, you can lazily initialized modules by just omitting `data-module` and then adding it later and calling `start()` or `startAll()` yourself. Even if we added something like `data-init-delay`, you'd still need to remove that attribute and call `start()` or `startAll()` yourself, so the work is the same.

**Comment by chchrist** [comment]
OK, good to know :)
So a module is like a Controller and a Mediator for a View in one?

**Comment by nzakas** [comment]
Yeah, I think that's an accurate description.
