### ISSUE TITLE
[question] Module loaders

### ISSUE THREAD

**Issue by chchrist** [box/t3js#60]
I am wondering if using a module loader like requireJS, webpack etc is a good practise for a t3js project.
Because this way you could require a service instead of using the Application object API.

**Comment by rui-infotrack** [comment]
@chchrist I'd say you don't need to choose only either this or that; you can mix them up. For my project, I use Application object API to hold modules, services, behaviors, but also use require(...) (I use browserify) to access other objects such as constants, React components etc.

As far as I see, there is not strict rule for this (yet).

**Comment by nzakas** [comment]
Yeah, there's definitely no strict rule. We created services due to the lack of `require` in the browser (this was before browserify/webpack had become popular). It makes complete sense to use CommonJS modules instead of services because they give you the same affordance for scope control.

We've theorized that if we moved to a pure CommonJS world, that services would more or less go away because we could use CommonJS modules to achieve the same thing.
